<?php
return [
  [
    'title' => '内容',
    'icon' => 'aicon ai-shezhi',
    'module' => 'cms',
    'url' => 'cms',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 100,
    'childs' => [
      [
        'title' => '内容管理',
        'icon' => 'typcn typcn-folder',
        'module' => 'cms',
        'url' => 'cms',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '内容管理',
            'icon' => 'typcn typcn-th-menu',
            'module' => 'cms',
            'url' => 'cms/content/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 1,
            'childs' => [
              [
                'title' => '添加内容',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/content/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改内容',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/content/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除内容',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/content/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '恢复内容',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/content/restore',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '排序设置',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/nav/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '栏目管理',
            'icon' => 'typcn typcn-th-list-outline',
            'module' => 'cms',
            'url' => 'cms/category/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 2,
            'childs' => [
              [
                'title' => '添加栏目',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/category/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改栏目',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/category/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除栏目',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/category/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '状态设置',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/category/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '排序设置',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/category/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '推荐管理',
            'icon' => 'typcn typcn-thumbs-up',
            'module' => 'cms',
            'url' => 'cms/rec/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 3,
            'childs' => [
              [
                'title' => '推荐位管理',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/rec/position',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '添加推荐位',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/rec/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改推荐位',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/rec/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除推荐位',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/rec/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '推荐位排序',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/rec/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '碎片管理',
            'icon' => 'typcn typcn-th-small',
            'module' => 'cms',
            'url' => 'cms/block/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 4,
            'childs' => [
              [
                'title' => '添加碎片',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/block/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改碎片',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/block/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/block/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '标签管理',
            'icon' => 'typcn typcn-tags',
            'module' => 'cms',
            'url' => 'cms/tag/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 5,
            'childs' => [
              [
                'title' => '删除标签',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/tag/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '模型管理',
            'icon' => 'typcn typcn-point-of-interest-outline',
            'module' => 'cms',
            'url' => 'cms/model/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 6,
            'childs' => [
              [
                'title' => '添加模型',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/model/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改模型',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/model/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除模型',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/model/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '状态设置',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/model/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '排序设置',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/model/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '栏目类型',
            'icon' => 'typcn typcn-th-large-outline',
            'module' => 'cms',
            'url' => 'cms/type/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 7,
            'childs' => [
              [
                'title' => '添加类型',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/type/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改类型',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/type/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除类型',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/type/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '状态设置',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/type/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '排序设置',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/type/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除属性项',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/type/del',
                'param' => 'hisiModel=CmsAttributeItem',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除属性值',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/type/del',
                'param' => 'hisiModel=CmsAttributeValue',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '字段管理',
            'icon' => '',
            'module' => 'cms',
            'url' => 'cms/field/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 0,
            'sort' => 8,
            'childs' => [
              [
                'title' => '添加字段',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/field/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改字段',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/field/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除字段',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/field/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '排序设置',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/field/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '扩展功能',
        'icon' => 'typcn typcn-puzzle-outline',
        'module' => 'cms',
        'url' => 'cmsExtend',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 2,
        'childs' => [
          [
            'title' => '幻灯片',
            'icon' => 'typcn typcn-image-outline',
            'module' => 'cms',
            'url' => 'cms/slide/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加幻灯片',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/slide/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改幻灯片',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/slide/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除幻灯片',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/slide/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '状态设置',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/slide/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '排序设置',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/slide/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '导航管理',
            'icon' => 'typcn typcn-compass',
            'module' => 'cms',
            'url' => 'cms/nav/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加导航',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/nav/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改导航',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/nav/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除导航',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/nav/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '表单管理',
            'icon' => 'typcn typcn-document-text',
            'module' => 'cms',
            'url' => 'cms/form/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 1,
            'childs' => [
              [
                'title' => '添加表单',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/form/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改表单',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/form/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除表单',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/form/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '状态设置',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/form/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '查看代码',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/form/code',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '表单字段管理',
            'icon' => '',
            'module' => 'cms',
            'url' => 'cms/formField/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 0,
            'sort' => 2,
            'childs' => [
              [
                'title' => '添加表单字段',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/formField/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改表单字段',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/formField/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除表单字段',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/formField/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '表单字段排序',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/formField/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '表单内容管理',
            'icon' => '',
            'module' => 'cms',
            'url' => 'cms/formContent/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 0,
            'sort' => 3,
            'childs' => [
              [
                'title' => '修改表单内容',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/formContent/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '查看表单内容',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/formContent/show',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除表单内容',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/formContent/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 1,
              ],
            ],
          ],
          [
            'title' => '友情链接',
            'icon' => 'typcn typcn-link-outline',
            'module' => 'cms',
            'url' => 'cms/link/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 5,
            'childs' => [
              [
                'title' => '添加链接',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/link/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改链接',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/link/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除链接',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/link/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '状态设置',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/link/status',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '排序',
                'icon' => '',
                'module' => 'cms',
                'url' => 'cms/link/sort',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '评论管理',
            'icon' => 'typcn typcn-edit',
            'module' => 'cms',
            'url' => 'cms/comment/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 0,
            'sort' => 6,
          ],
        ],
      ],
    ],
  ],
];
