<?php
return [
  [
    'title' => '首页',
    'icon' => '',
    'module' => 'system',
    'url' => 'system/index',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 1,
    'nav' => 1,
    'sort' => 10,
    'childs' => [
      [
        'title' => '快捷菜单',
        'icon' => 'aicon ai-caidan',
        'module' => 'system',
        'url' => 'system/quick',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 1,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '系统信息',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/index/sysinfo',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 1,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 1,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 1,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 2,
            'childs' => [
              [
                'title' => '设置默认等级',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/member/setdefault',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '重置密码',
                'icon' => '',
                'module' => 'system',
                'url' => 'system/member/resetPwd',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 1,
                'nav' => 1,
                'sort' => 6,
              ],
            ],
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 2,
          ],
          [
            'title' => '清空缓存',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/index/clear',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 2,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 2,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 3,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 4,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 4,
          ],
          [
            'title' => '个人信息设置',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/user/info',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 5,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 5,
          ],
          [
            'title' => '后台首页',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/index/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '后台首页',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/index/welcome',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '布局切换',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/user/iframe',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '钩子插件状态',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/hook/hookPluginsStatus',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '设置主题',
            'icon' => '',
            'module' => 'system',
            'url' => 'system/user/setTheme',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 0,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
          [
            'title' => '预留占位',
            'icon' => '',
            'module' => 'system',
            'url' => '',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 1,
            'nav' => 1,
            'sort' => 100,
          ],
        ],
      ],
    ],
  ],
];
